Modified install to ignore mapping copy errors since they intentionally fail on the production server
git-svn-id: https://aeon.stsci.edu/ssb/svn/crds_server/trunk@981 37088bc5-bd3f-4c5b-b9de-119bb1e8f7e3

diff --git a/install b/install
--- a/install
+++ b/install
@@ -368,10 +368,12 @@ echo
 echo "Copying prototype mappings from ${mapping_source_dir} to ${map_path_full}"
 echo
 create_dir $public ${map_path_full}
+set +e # tolerate errors
 for mapping in `ls -1 ${mapping_source_dir}/*.*map | grep -v 0`;
 do
   cp -v ${mapping} ${map_path_full} 2>/dev/null 1>/dev/null
 done
+set -e # fail on errors
 
 # chmod $immutable ${map_dest}/*.*map
 
@@ -443,6 +445,6 @@ case ${observatory}
 esac
 
 echo "Silently installing static files."
-./manage collectstatic >/dev/null <<EOF
+./manage collectstatic <<EOF
 yes
 EOF
